# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34110206c287992541b0c57019bfb05ed45cd4b7fd662bcf9a76bd16a7f2c52a9a1a1befab45fc8ea7a5321f1b2a3ed22ceeb98f09e135a3d50e7d15d7d8007f

test:
  secret_key_base: 1700a20dca4d924356693f34c5eb4fe088059863d0af29b96c740b7903a9c3845f195df8568fa46a92b11bee2e8f5f968863a7e03613f02f9b62dc7a52367716

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
